name: Makefile CI

on:
  push:
    branches: 
    - feat/api-integration
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: make install
