name: Test CI

on:
  push:
    branches:
      - test/api-integration
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: make test
